---
 - name: doing update
   apt:
     update_cache: yes
  
 - name: Install some packages
   action: apt name={{ item }} state=present
   with_items: "{{ pkg }}"

 - name: adding jenkins key to system
   apt_key: 
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present   

 - name: adding jenkins repo to sourced.list     
   apt_repository:
      repo: deb http://pkg.jenkins.io/debian-stable binary/
      state: present
      filename: jenkins.list

 - name: doing update
   apt:
     update_cache: yes

 - name: install jenkins
   action: apt name=jenkins state=present
   notify: start jenkins service
 
 - name: jenkins status check
   shell:
   args: 
     cmd: systemctl status jenkins
   register: myresult

 - name: debugme
   debug:
      var: myresult
  

     